name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 18 ]
      fail-fast: false

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: install canvas dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

    - name: npm ci
      run: npm ci

    - name: npm audit production
      run: npm audit --omit=dev

    - name: npm run build
      run: npm run build

    - name: npm test
      run: npm test

    - name: npm run tap-junit-report
      run: npm run tap-junit-report || true

    - name: upload artifact
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
          name: 'qrcode-tests-report-nodejs_${{ matrix.node }}'
          path: 'test-results.xml'
          compression-level: 0

    - name: test report
      uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8 # 1.8.0
      if: success() || failure()
      with:
        name: 'qrcode-tests-nodejs_${{ matrix.node }}_${{ runner.os }}'
        path: 'test-results.xml'
        reporter: jest-junit

    - name: npm pack
      if: always()
      run: npm pack

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: qrcode_nodejs_${{ matrix.node }}
          path: '*.tgz'
          compression-level: 0
